[features]
seeds = false
skip-lint = false

[programs.localnet]
cargo = "6fB9WUia2btTZagzbcrXvoga5VXYJGqa7J8P2rFjEb5b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/jessie/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
